name: Ktlint

on:
  push:
    branches: [ "master" ]
    paths:
      - .github/workflows/ktlint.yml
      - 'src/**/*.kt'
      - '**.kts'
  pull_request:
    branches: [ "master", "develop" ]
    paths:
      - .github/workflows/ktlint.yml
      - 'src/**/*.kt'
      - '**.kts'


    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check Ktlint with Gradle
        run: ./gradlew ktlintCheck buildSrc:ktlintCheck
